# Site settings
title: Procrastinative Ninja
email: sebastian@lurado.de
description: "what I do, when I don't do, what I should do."
baseurl: ""
url: "http://procrastinative.ninja"
highlighter: pygments

timezone: Europe/Berlin

# Build settings
markdown: redcarpet
permalink: pretty

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "superscript"]

owner:
  name: Sebastian Ludwig
  disqus_shortname: procrastinativeninja
  github_username:  sebastianludwig

# Frontmatter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: post
    values:
      layout: post
