# Site settings
title: Procrastinative Ninja
email: sebastian@lurado.de
description: "what I do, when I don't do, what I should do."
baseurl: ""
url: "https://procrastinative.ninja"

timezone: Europe/Berlin

# Build settings
permalink: pretty
exclude: ['Gemfile', 'Gemfile.lock', 'TODO.txt', '*.psd']

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true

owner:
  name: Sebastian Ludwig
  disqus_shortname: procrastinativeninja
  github_username:  sebastianludwig

# Frontmatter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      layout: post

gallerytag:
    dir: media/images/galleries
    url: /media/images/galleries
    thumb_width: 136
    thumb_height: 136
    columns: 4
    magick_lib: mini
